modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="wcwt.mixins.json"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
mandatory=true
versionRange="[15.4.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2wtlib"
mandatory=true
versionRange="[${ae2wtlib_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="advanced_ae"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="expatternprovider"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="extendedae_plus"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2importexportcard"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
